# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs
require 'pry'
time1 = Time.now
puts 'Start recreate database'
Team.delete_all
Member.delete_all

puts 'Deleted all records'
teams = ['arsenal', 'manchester united']
players = [['Santi', 'cazorla',1], ['lucas', 'podolski',1], ['Wayne', 'rooney', 2], ['robin van', 'persie',2]]
puts 'Teams'
teams.each do |t|
  x = Team.new
  x.name = t.titleize
  x.save
  puts "Team #{t.titleize} has been inserted."
end
puts 'Players'
players.each do |p|
  x = Member.new
  x.firstname = p[0].titleize
  x.lastname = p[1].upcase
  x.team_id = p[2]
  x.save
  puts "Player #{p[0].titleize} #{p[1].upcase} has been inserted."
end
puts 'End recreate database'
total_time = Time.now - time1
puts "Completed in #{total_time} #{'second'.pluralize(total_time)}"

